myapp/urls.py
from django.urls import path
from myapp import views 
app_name = 'myapp'

urlpatterns = [
    path('front/',views.front,name = 'fr'),
    path('about/',views.about,name = 'ab'),
    path('mail/',views.usermail,name = 'ma'),
    
    path('mobiles/',views.mobiles,name = 'mobile'),
    path('registration/',views.registration,name = 'registration'),
    path('uslogin/',views.uslogin,name = 'uslogin'),
    path('uslogout/',views.uslogout,name = 'uslogout'),
    path('dashboard/',views.dashboard,name = 'dashboard'),
    path('profile/',views.profile,name = 'profile'),
    path('changeprofile/',views.change_profile,name = 'change_profile'),
    path('changepass/',views.change_password,name = 'change_password'),
    path('addcart/',views.addcart,name = 'cart'),
    path('getproduct/',views.getproduct,name = 'getproduct'),
    path('singleproduct/',views.singleproduct,name = 'singleproduct'),
    path('orders/',views.my_orders,name = 'myorders'),

    path('removecart/',views.removeCart,name='removecart'),
    path('grandTotal/',views.grandTotal,name='grandTotal'),
    path('sendMail/',views.sendMail,name='sendMail'),
    path('get_order/',views.get_order, name='get_order'),
    path('success_payment/',views.success_payment, name='success_payment'),
    path('order_details/',views.order_details, name='order_details'),
    path('pending_orders/',views.pending_orders, name='pending_orders'),
    path('uservalid/',views.uservalid,name='uservalid'),
    

    

    
    








    



   

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.front,name='index'),
    path('myapp/',include('myapp.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/aboutus.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
<style>
    .banner{
    width:100%;
    height:500px;
    background: url("{%static 'images/b1.jpg'%}");
    background-size: 100% 100%;
    position: relative;
    float: left;
    }
    .ab{
        width:100%;
    }
    .para{
        font-size:15px;
        font-family:'Vollkorn', serif;
        text-align:left;
        padding-left:50px;
        color:grey;
    }
    .pic{
        width:100%;
        background-size:cover;
    }
    .ps{
        width:100%;
        font-family:'Vollkorn',serif;
        text-align:center;padding-top:10px;
    }
    .txt{
        width:100%;
        color: lightgrey;
        font-family:'Vollkorn',serif;  
    }
    .offer{
        width:100%;
        background: white;
        text-align: center;
        font-family:'Vollkorn',serif;
    }
    .las{
        width:100%;
        font-family:'Vollkorn',serif;
    }
    </style>
</head>
<body>
        <div class='row'>
                <div class='banner  px-0 mx-0'></div>
            <div class='nav1 col-md-12 text-center m-0 px-0 pt-3'style="font-family:'Vollkorn',serif; width:100%; background: #ccc;"><i class="fas fa-home"></i>Home / About Us</div>
        </div>
        <div class='row'>
            <div class='ab col-md-6 mt-5 text-gray justify-content-end'>
            <p class='para'>Our Team are aimed to provide the customers facility to buy their own household<br/> goods and products online anytime and anywhere.This website can gives the <br/>customers 
                an option of integrating with diverse payment gateways by not<br/> limiting your choices to a selected few.
            </p><br><br>
                <p class='para'style="padding-left:100px;"><i class="fas fa-share-square" style="color:red;"></i>&nbsp;&nbsp;&nbsp;An order management panel simplifies the task of the merchant where one can get detailed information regarding buyer Cancellation /Refunds/
                     COD order Verification/ Exchange/ Order Status/ Update and more.</p>
           <br><br>
            <p class='para' style="padding-left:100px;"><i class="fas fa-bolt" style="color:red;"></i>&nbsp;&nbsp;&nbsp;It also includes the entire online process 
                of developing, marketing, delivering, servicing and paying for products and services.</p>
            </div>
            <div class='pic col-md-6 mt-5 justify-content-center'>
                <img src='{%static "images/cam.jpg"%}' alt="">
            </div>
        </div>
        <div class='row'>
            <div class=' ps col-md-12 bg-light'>
                <div class='row'>
                    <div class='col-md-12'>
                    <h1 class='mt-5'>MEET OUR TEAM</h1>
                    </div>
                </div>
                    <div class='row'>
                        <div class='col-md-3 mt-5'>
                            <div>
                                    <img src='{%static "images/t4.png"%}' alt="" style="border:7px solid white; border-radius:50%;box-shadow:0px 0px 10px red;">
                            </div>
                            <h4 class='mt-3'>Smith Allen</h4>
                            <span>Manager</span>
                            <div class='row'>
                                <div class='col-md-6 mx-auto'>
                                    <!-- <div class='row'>
                                        <div class='col-md-3 mt-3'>
                                            <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-facebook-f"></i></div> 
                                            </div>
                                            <div class='col-md-3 mt-3'>
                                            <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-twitter"></i></div> 
                                            </div>
                                            <div class='col-md-3 mt-3'>
                                            <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-google-plus-g"></i></div> 
                                            </div>
                                            <div class='col-md-3 mt-3'>
                                            <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-pinterest-p"></i></div> 
                                            </div>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                        <div class='col-md-3 mt-5'>
                            <img src='{%static "images/t5.png"%}' alt="" style="border:7px solid white; border-radius:50%; box-shadow:0px 0px 10px red;">
                            <h4 class='mt-3'>Laura James</h4>
                            <span>Designer</span>
                            <div class='row'>
                                    <div class='col-md-6 mx-auto'>
                                        <!-- <div class='row'>
                                            <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-facebook-f"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-twitter"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-google-plus-g"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-pinterest-p"></i></div> 
                                                </div>
                                        </div> -->
                                    </div>
                                </div>
                        </div>
                        <div class='col-md-3 mt-5'>
                            <img src='{%static "images/t6.png"%}' alt="" style="border:7px solid white; border-radius:50%; box-shadow:0px 0px 10px red;">
                            <h4 class='mt-3'>Crisp Doe</h4>
                            <span>Director</span>
                            <div class='row'>
                                    <div class='col-md-6 mx-auto'>
                                        <!-- <div class='row'>
                                            <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-facebook-f"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-twitter"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-google-plus-g"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-pinterest-p"></i></div> 
                                                </div>
                                        </div> -->
                                    </div>
                                </div>
                        </div>
                        <div class='col-md-3 mt-5'>
                            <img src='{%static "images/t7.png"%}' alt="" style="border:7px solid white; border-radius:50%; box-shadow:0px 0px 10px red;">
                            <h4 class='mt-3'>Linda Rosy</h4>
                            <span>Quality Checker</span>
                            <div class='row'>
                                    <div class='col-md-6 mx-auto'>
                                        <!-- <div class='row'>
                                            <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-facebook-f"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-twitter"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-google-plus-g"></i></div> 
                                                </div>
                                                <div class='col-md-3 mt-3'>
                                                <div class='btn btn-dark text-white' style="width:35px;height:40px;"><i class="fab fa-pinterest-p"></i></div> 
                                                </div>
                                        </div> -->
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class='row'>
                        <div class='txt col-md-12 text-center  mt-5'>
                            <p>Our Team members can check the profile of user and check their orders. Also the admin manage<br/> the product to be delivered on time. •	It also includes the entire online<br/> process of developing, marketing, delivering, servicing <br/>and paying for products and services</p>
                        </div>
                    </div>
            </div>
        </div>
<!--Deals-->
        <div class='row'>
            <div class='offer col-md-12 mt-5'>
                <h3>Are You Ready For Deals?Flat<span style="color:darkblue;">30% Offer</span> On Mobiles</h3><br>
                <span>We give you exciting offers on all products that you can check on the orders. Also the admin<br/> manage the product to be delivered on time. •	It also includes the entire online<br/> process of developing, marketing, delivering, servicing <br/>and paying for products and services</span>
                     <h5 class='mt-5' style="text-align:center; "> <a href="{%url 'myapp:mobile'%}" style='color:red;'>Shop Now &rarr;</a></h5>
            </div>
        </div>
{% endblock %}

templates/cart.html
{% extends "dashboard.html"%}
{% load staticfiles %}
{% block content %}
<style>
        .spinnerouter{
            background:rgb(0,0,0,0.5);position:fixed;width: 100%;height: 100%;z-index:99999;
            top:0px;display: none;}
        .loader {
            border: 16px solid #f3f3f3; /* Light grey */
            border-top: 16px solid rgb(60, 67, 164); /* Blue */
            border-radius: 50%;
            width: 120px;
            height: 120px;
            animation: spin 1s linear infinite;
            position: absolute;
            left:45%;
            top:45%;
            z-index:999999;
        }
        .spinner-border{
            height:25px;width:25px;border:5px solid white;border-top:5px solid #f0ad4e;
            animation: spin 1s linear infinite;border-radius:50%;margin:auto;
        }
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        table,td{
        color:black !important;
       }
    
    
    </style>
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"> -->
    <div class="spinnerouter">
        <div class="loader">
    
        </div>
    </div>
<div class="container">
        
    <h2 style="font-family: 'Noticia Text', serif;" class="mt-2">MY CART</h2>
    <div style='height:2px;width:100px;background:#ff5063'></div>
    <br>
    <div class='row'>
        {% if status %}
        <script>
            alert('{{status}}');
            window.location = '/'
        </script>
        {% endif %}
        <div class='col-md-12'>
            {% if messages %}
            {% for i in messages %}
                <div class="alert alert-{{i.tags}}  status">{{i}}</div>
            {% endfor %}
            {% endif %}
        </div>
        {% if cart_size is 0 %}
        <div class='col-md-12' style='padding:20px;' id='empty'>
            <h2>❌ Your Shopping Cart is Empty</h2>
        </div>
        {% else %}
        
            <div class='col-md-8'>
                <h2>My Cart(<spanid='csize'>{{cart_size}}</span> )</h2>
                <hr/>
                <ul class='list-group'>
                    {% for i in cart %}
                    <li class='list-group-item c-{{i.id}}' style='box-shadow:0px 0px 10px black;'>
                        <div class='row'>
                            <div class='col-md-7' style='text-align:center;font-size:30px;'>
                                <span>
                                    <img src="/media/{{i.photo}}" style='border-radius:50%;margin:10px;' height='70' width='70' class='rounded-circle'>
                                   <div class='form-group'>
                                    
                                        <div class='row'>
                                            <div class='col-md-3 col-sm-3 col-3'>
                                                <span onclick="addNum('{{i.id}}','add')">
                                                    <i class="fas fa-plus-circle text-success"></i>
                                                </span>
                                            </div>
                                            <div class='col-md-6 col-sm-6 col-6'>
                                                <input type="number" id="num" value='{{i.quantity}}' class='form-control num{{i.id}}'>
                                            </div>
                                            <div class='col-md-3 col-sm-3 col-3'>
                                                <span onclick="addNum('{{i.id}}','sub')">              
                                                    <i class="fas fa-minus-circle text-danger"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                            </div>
                            <div class='col-md-5'>
                                <span class='text-danger font-weight-bold'>
                                    <strong>{{i.product_name}}</strong><br/>
                                    |{{i.product_cat}} | {{i.brand}}
                                </span><br>
                                <h4 STYLE='margin-top:20px;'><strong class='text-success cartsaleprice{{i.id}}'>&#8377;{{i.price}}</strong>
                                    <br> <del style='font-size:12px;' class='cartprice{{i.id}}'> &#8377; {{i.market}}</del>
                                  <br>  <span style='color:green;font-family:arial'>You save {{i.offer}}%</span>
                                </h4>
                            </div>
                        </div> 
                        <hr/>
                    </li>           
                    {% endfor %}
                </ul>    
            </div>
            <div class='col-md-4'>
                {% if cart_size is not  0 %}
                <h2>Price Details</h2>
                <hr/>
                <div style='padding:10px;border-radius:5px;'>
                    <table class='table'>
                        <tbody>
                            <tr>
                                <td id='itotal'>ITEM TOTAL</td>
                                <td id='total'></td>
                            </tr>
                            <tr style='border-bottom:1px dotted gray;'>
                                <td>DELIVERY CHARGES</td>
                                <td>FREE</td>
                            </tr>
                            <tr>
                                <td><strong>GRAND TOTAL</strong></td>
                                <td id='grand'></td>
                            </tr>
                            
                        </tbody>
                    </table>
                    <hr/>
                    <div style='padding:10px; display:none;' id='delivery_address'>
                        <h4>Enter Delivery Details</h4>
                        <hr/>
                        
                            <div class='form-group'>
                                <input type="text" class='form-control' placeholder='Enter Name' id='dname' required>
                            </div>
                            <div class='form-group'>
                                <!-- <label for="" id='res'></label> -->
                                <input type="email" class='form-control' placeholder='Enter Email Address' id='demail' required>
                            </div>
                            <!-- <div class='form-group' style='display:none;'>
                                <input type="number" class='form-control' placeholder='Enter OTP Here' id='id_enter_otp'>
                            </div> -->
                            <div class='form-group'>
                                <input type="number" class='form-control' placeholder='Enter Mobile Number' id='dnumber' required>
                            </div>
                            <div class='form-group'>
                                <textarea name="daddress" id="daddress" class='form-control' placeholder='Enter Full Address' required></textarea>
                            </div>
                            <div class='form-group'>
                                <input type="hidden" id='grandtotal'>
                                <input type="hidden" id='items' value='{{cids}}'>
                                <button class='btn btn-success btn-block' id='ptp'>Proceed To Pay</button>
                            </div>
                        

                    </div>
                    <button class='btn btn-warning btn-block' id='ptb'><i class='fas fa-shopping-cart'></i> Proceed To Buy</button>
                </div>
                {% endif %}
            </div>
      
        {% endif %}
    </div>
</div>
<script>
function addNum(id,action){
    $('.spinnerouter').show();
    let v = $('.num'+id).val();
    let updateQuant = 0;
    if(action=='add'){
        updateQuant = parseInt(v)+1;    
    }else{
        updateQuant = parseInt(v)-1;    
    }
    setTimeout(function(){
        $.ajax({
            url:'{% url "myapp:cart" %}',
            type:'get',
            data:{q:updateQuant,id:id},
            success:function(data){
                $('.num'+id).val(data.quantity);
                $('.cartsaleprice'+id).html(data.sale_price*data.quantity);
                $('.cartprice'+id).html(data.price*data.quantity);
                $('.spinnerouter').hide();
                $('#csize').html(data.cart_size);
                grandTotal()

                // #Remove Items
                if(data.quantity==0){
                $.ajax({
                    url:'{% url "myapp:removecart" %}',
                    data:{removeid:id},
                    success:function(data){
                        $('.c-'+id).hide();
                        $('.status').html(data.msz);
                        $('#csize').html(data.cart_size);
                    }
                });
            }              
            }
        });
    });
}
</script>

<script>
    let email;
function grandTotal(){
    $.ajax({
        url:'{%url "myapp:grandTotal"%}',
        success:function(data){
            $('#itotal').html('ITEM TOTAL ('+data.quantity+')');
            $('#total').html('&#8377;'+data.grand_total);
            $('#grand').html('&#8377;'+data.grand_total);
            $('#demail').val(data.email)
            $('#dname').val(data.name)
            $('#daddress').val(data.address)
            $('#grandtotal').val(data.grand_total);
            $('#ptp').html('Proceed To Pay &#8377;'+ data.grand_total)
        }
    });
}
grandTotal();
</script>
<script>
$('#ptb').click(function(){
    $(this).html('<div class="spinner-border"></div>');
    setTimeout(function(){
        $('#delivery_address').slideDown(1000);
        $('#ptb').hide();
    },1500);
});
</script>

<!-- VERIFICATION EMAIL --> 
<script>
var arr = [];
$('#dnu').focus(function(){
    var name = $('#dname').val();
    var email = $('#demail').val();
    $.ajax({
    url:'{% url "myapp:sendMail"%}',
    data:{name:name,email:email},
    success:function(data){
        arr = data.split('@');
        $('#res').html(arr[0]).addClass('text-success');
        $('#id_enter_OTP').show();
    }
    });
});
</script>

<script>
$('#ptp').click(function(){
    let dname = $('#dname').val();
    let demail = $('#demail').val();
    let daddr =$('#daddress').val();
    let dcon = $('#dnumber').val();
    let amount = $('#grandtotal').val();
    let it = $('#items').val();
    $.ajax({
        url:'{% url "myapp:get_order"%}',
        type:'get',
        data:{'grandtotal':amount,'dname':dname,'demail':demail,'daddress':daddr,'dnumber':dcon,'items':it},
        success:function(data){
            let oid = parseInt(data)+Math.round(Math.random()*(9999-1000)+1000)
            url = 'http://sachtechsolution.pe.hu/easypayment/payment.php?mid=TZDvAt43006325246934&amount='+amount+'&adminemail=dipaligarg502@gmail.com&adminmobile=9876343502&mkey=VZWE%23%26sP5OgFWwmk&orderid='+data+'o'+oid+'&returnurl=http://127.0.0.1:8000{% url "myapp:success_payment" %}';
            window.location = url; 
        }
    })
    
})
</script>
{% endblock %}
    

templates/dashboard.html
{% extends "base.html"%}
{% block mystyle %}
{% endblock %}
{% block body %}
<div class='container-fluid'>
<div class="row">
  <div class="col-md-3">
       
        <div class="row">
                <div class="col-md-12 text-center mt-2" style="border: 2px solid black ; color: slategray">
                    <h4 style="font-family: 'Noticia Text', serif; font-size: 30px;" class="p-3">
                        <i class="far fa-address-card" style="font-size:30px;"></i>
                        <span class="ml-1">MANAGE PROFILE</span></h4>
                    <h5><a href="{%url 'myapp:profile'%}"><span style="font-family: 'Noticia Text', serif;">My Profile</a> </span></h5>
                    <h5><a href="{%url 'myapp:change_profile'%}" ><span style="font-family: 'Noticia Text', serif;">Change Profile</a></span></h5>
                    <h5><a href="{%url 'myapp:change_password'%}"> <span style="font-family: 'Noticia Text', serif;">Change Password</a></span></h5>
        </div></div>
        <div class="row">
                <div class="col-md-12 text-center mt-2" style="border: 2px solid black ; color: slategray">
                    <h4 style="font-family: 'Noticia Text', serif; font-size: 30px;" class="p-3">
                            <i class="fas fa-cart-arrow-down"></i>
                            <span class="ml-1">MY ORDERS</span></h4>
                    <h5><a href="{%url 'myapp:myorders'%}" > <span style="font-family: 'Noticia Text', serif;">Order History</span></a></h5>
                    <h5><a href="{%url 'myapp:pending_orders'%}" ><span style="font-family: 'Noticia Text', serif;">Pending Orders</span></a></h5>
                    
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 p-2 text-center mt-2" style="border: 2px solid black ; color: slategray">
           <h5>
               <a href="{%url 'myapp:uslogout' %}"><i class="fas fa-sign-out-alt"></i> 

            <span style="font-family: 'Noticia Text', serif;" class="ml-1" >Logout</span></a></h5>   
        </div>
    </div>
  </div>
  <div class="col-md-7 ">
      {% block content %}
      {% endblock %}
  </div>
</div>
</div>
{% endblock %}

templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="GET">
      <input type="text" name="key">
      <input type="submit">
    </form>
</body>
</html>

templates/pending.html
{% extends "dashboard.html" %}
{% load staticfiles%}
{% block style %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src='//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js'></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'mystyle.css'%}">
<style>
.ab{
    border:1px solid black !important;
}
</style>
{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <h2 class='py-5'>Pending Orders</h2>
    <table class='table table-striped table-hover table-bordered' id='myTable' style=" font-family:'Vollkorn',serif;">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Total Price</th>
                <th>Received On</th>
                <th>Processed On</th>
                <!-- <th>View Items</th> -->
            </tr>
        </thead>
        <tbody>
            {% for i in pending_orders %}
                <tr>
                    <td>{{i.id}}</td>
                    <td>{{i.amount}}</td>
                    <td>{{i.received_on}}</td>
                    <td>{{i.changed_on}}</td>
                    <!-- <td>
                        <a href="{% url 'myapp:order_details'%}?id={{i.id}}"><button class='btn btn-sm btn-primary'>View</button>
                    </td> -->

                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
    $(function(){
        $('#myTable').DataTable();
    })
    </script>
{% endblock %}

templates/process.html
{% extends "dashboard.html"%}
{% load staticfiles%}
{% block content %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-12' style='padding:40px;'>
                <div style='height:400px;width:100%;border:1px solid black;padding:50px;border-radius:5px;'>
                    {% if status %}
                        {{status}}
                        <a href="{% url 'myapp:dashboard'%}">Go Ho Homepage</a>
                    {% else %}
                    <div class='row'>
                        <div class='col-md-4'>
                            <h2 style='color:green;font-size:100px;'><i class="far fa-check-circle"></i></h2>
                        </div>
                        <div class='col-md-8'>
                            <h2 style='margin-top:10%;'>Order Success!!!</h2>
                        </div>
                        <div class='col-md-12'>
                            {% if status%}
                            <p class='alert alert-success'>{{status}}</p>
                            {% endif %}
                            <p class='text-success text-center' style='color:green;font-size:20px;'>
                                Hello {{user.username}} Your order with Txn No: {{txn_id}} received successfully!!!
                            </p>
                            <span class='text-info text-center' style="font-weight:bold;" >Thanks for choosing Electronic Store for shopping!!</span>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}